### ISSUE TITLE
Thors hammer

### ISSUE THREAD

**Issue by slvlr** [slvlr/TerrorPVP#26]
Could you add sharpness 1 or 2 onto thors hammer please. I can't do this as you hard-coded the hammer.

Also the hammer still breaks with item durability. Once its damaged the ability no longer works.

**Comment by rangewonk** [comment]
Both of these issues are still on the Thors hammer.

**Comment by rangewonk** [comment]
Thor still has no enchantments and the axe still breaks. The ability still works on a damage axe this time though once its completly breaks its gone.

**Comment by DebugingLonks** [comment]
Try to NBT Tag it "Unbreakable" not that hard to do :P
