### ISSUE TITLE
hub

### ISSUE THREAD

**Issue by slvlr** [slvlr/TerrorPVP#36]
/hub command should have a 3 second cooldown on it please?

**Comment by Mario1230X** [comment]
/hub doesn't even work rn, it needs to be remade to do /server hub

**Comment by DebugingLonks** [comment]
^ That was me xD

**Comment by DebugingLonks** [comment]
https://github.com/slvlr/TerrorPVP/blob/master/src/me/TerrorLT/TerrorPVP/Globals.java

Hub is testing for a world name. Is hub still named that? Anyway. This is due to Bungee. Doing /hub rn causes you to tp with your kit to the middle of kit, but you can't move.

**Comment by slvlr** [comment]
C
