### ISSUE TITLE
kit interface

### ISSUE THREAD

**Issue by slvlr** [slvlr/TerrorPVP#37]
we have many kits now, 

Could u make a way so I could add kits to the crate kit interface and the donator kit interface. 
Also a "next page" button at bottom line if needed.

Is there a way that I can put the kits into a certain order or could u make it so i can please?

**Comment by rangewonk** [comment]
Creating the "next page" button would be handy though if you could manage to set up the permissions and kit categories properly then you might not need to make a next page button yet as it will spread out the kits.
